### PR TITLE
Add Minio theme

### PR DESCRIPTION
**Pull request by rushenn**

### CODE REVIEW

**Review by deekoder — APPROVED** [review]

**Review by kaankabalak — DISMISSED** [review]
I think we would need to use the black Minio wordmark instead of the white one, as it isn't visible right now.

**Review by kaankabalak — COMMENTED** [review]
Also, something minor, but should the sidebar headers and active links be `#232323` instead of `#000000`?

**Comment by rushenn** [comment]
@kaankabalak I have updated the site.yml to use the darker logo. Please review.

> Also, something minor, but should the sidebar headers and active links be #232323 instead of #000000?

These state colors are based on the original design where `#000000` is used for both headers and active classes. 

36657002-ca20256e-1af0-11e8-8405-3b8541bce46b

(Above is a screenshot of the original UI. Active class is not working at the time but the idea was to have `#000`)

**Comment by kaankabalak** [comment]
@rushenn I think I used the wrong wording when I posted the first comment before editing it, I meant to ask you if you could replace the white wordmark with the black wordmark (instead of the black stork logo). Thanks in advance and sorry for the inconvenience.

**Comment by rushenn** [comment]
@kaankabalak Oh my bad I've used the wrong file. I'll fix it shortly.

**Comment by rushenn** [comment]
@kaankabalak Please check now

**Review by kaankabalak — APPROVED** [review]

**Pull request merged**
